version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - renit_network

networks:
  renit_network:
    driver: bridge

volumes:
  redis_data: